//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int IdCompra { get; set; }
        public int IdProducto { get; set; }
        public int IdSucursal { get; set; }
        public int Cantidad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Sucursales Sucursales { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
