//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string UsuarioLogin { get; set; }
        public string Contraseña { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdRol { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Sucursales Sucursales { get; set; }
    }
}
